# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-09 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='esalary',
            field=models.IntegerField(),
        ),
    ]
